### ISSUE TITLE
OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: labels_ids

### ISSUE THREAD

**Issue by wn1652400018** [liushulinle/CRASpell#2]
请问报如下错误怎么解决。不太会用tensorflow。tf1.14，python3.7。
tensorflow.python.framework.errors_impl.InvalidArgumentError: Key: label_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext_1]]
`2022-07-19 17:54:06.585078: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.585078: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.585079: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.585080: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.585079: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.585081: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.585078: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.585078: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.585261: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.585425: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.585578: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.585726: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_mask.  Can't parse serialized Example.
2022-07-19 17:54:06.585881: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.586023: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.586179: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.586350: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.586478: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.586596: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.586753: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.586914: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.587075: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.587216: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.587381: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.587516: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.587719: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.587903: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.588029: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.588155: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.588301: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.608222: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.608370: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.608543: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.608761: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.608971: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.609096: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.609239: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.609370: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.609532: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.609641: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.609754: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.609894: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.610038: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.610166: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.610324: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.610455: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.610613: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.610730: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.610822: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.610985: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_mask.  Can't parse serialized Example.
2022-07-19 17:54:06.611127: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.611255: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.611406: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.611544: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.611700: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.611819: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.623638: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.623781: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.624002: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.624212: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.624389: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.624663: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.624811: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.624945: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.625097: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_mask.  Can't parse serialized Example.
2022-07-19 17:54:06.625244: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.625382: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.626553: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.626724: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.626893: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.627058: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_mask.  Can't parse serialized Example.
2022-07-19 17:54:06.627226: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_mask.  Can't parse serialized Example.
2022-07-19 17:54:06.627397: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.627583: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.627769: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.625681: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.625821: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.625961: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.626121: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.626261: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.626419: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.625539: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.652520: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.652642: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.652770: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.652943: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.653093: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.654222: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.653344: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.653500: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.653614: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.653802: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.653912: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.654072: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.653206: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.654397: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.654578: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.654736: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.654877: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.655011: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.655160: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.655329: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.655450: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.655606: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.668172: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.668292: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.668497: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.668630: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.668789: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.668895: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.669051: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.669212: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.669367: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.669502: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_mask.  Can't parse serialized Example.
2022-07-19 17:54:06.669628: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.669761: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.669867: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.670014: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.670158: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.670295: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.670432: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.670564: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.670709: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.670840: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.670992: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.671124: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.671257: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.683611: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.683673: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.683768: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: label_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.683947: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.684041: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: lmask.  Can't parse serialized Example.
2022-07-19 17:54:06.684181: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_mask.  Can't parse serialized Example.
2022-07-19 17:54:06.684352: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: input_ids.  Can't parse serialized Example.
2022-07-19 17:54:06.684491: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Key: segment_ids.  Can't parse serialized Example.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\b4k\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "C:\ProgramData\Anaconda3\envs\b4k\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\ProgramData\Anaconda3\envs\b4k\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Key: label_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext_1]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/workspace/pycharm/CRASpell/src/train_eval_tagging.py", line 193, in <module>
    train(FLAGS)
  File "D:/workspace/pycharm/CRASpell/src/train_eval_tagging.py", line 148, in train
    f1 = evaluate(FLAGS, sess, model, test_data_processor)
  File "D:/workspace/pycharm/CRASpell/src/train_eval_tagging.py", line 40, in evaluate
    inputs, loss_value, preds, golds, gmask = sess.run([input_ids, pred_loss, pred_result, gold_result, gold_mask])
  File "C:\ProgramData\Anaconda3\envs\b4k\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda3\envs\b4k\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\ProgramData\Anaconda3\envs\b4k\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "C:\ProgramData\Anaconda3\envs\b4k\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Key: label_ids.  Can't parse serialized Example.
	 [[{{node ParseSingleExample/ParseSingleExample}}]]
	 [[IteratorGetNext_1]]
`

**Comment by liushulinle** [comment]
这个可能是tf版本不对，具体原因还得自行排查
